const fs = require('fs');
const N = String.fromCharCode(10);
const Q = String.fromCharCode(34);
const S = String.fromCharCode(39);

// ExternalEditorIntegration.tsx
const extEditor = [
  "import { useState, useMemo } from 'react'",
  "import { useTx } from './i18n'",
  "",
  "interface EditorDef { id: string; name: string; cmd: string; detect?: boolean }",
  "",
  "const KNOWN_EDITORS: EditorDef[] = [",
  "  { id: 'vscode', name: 'VS Code', cmd: 'code -g {{file}}:{{line}}', detect: true },",
  "  { id: 'vscodium', name: 'VSCodium', cmd: 'codium -g {{file}}:{{line}}', detect: true },",
  "  { id: 'sublimetext', name: 'Sublime Text', cmd: 'subl {{file}}', detect: true },",
  "  { id: 'notepadpp', name: 'Notepad++', cmd: '\"C:\\\\Program Files\\\\Notepad+++\\\\notepad++.exe\" -g {{file}}:{{line}}', detect: true },",
  "]",
  "",
  "const CUSTOM_KEY = 'pv:custom-editors'",
  "",
  "export default function ExternalEditorIntegration(p: {",
  "  onConfigured: (chosen: string) => void",
  "}) {",
  "  const tx = useTx()",
  "  const [editors, setEditors] = useState<EditorDef[]>(() => {",
  "    try { return [...KNOWN_EDITORS, ...JSON.parse(localStorage.getItem(CUSTOM_KEY) || '[]')] }",
  "    catch { return KNOWN_EDITORS }",
  "  })",
  "  const [chosen, setChosen] = useState(() => localStorage.getItem('pv:editor-choice') || '')",
  "  const [customCmd, setCustomCmd] = useState('')",
  "",
  "  const detectStatus = useMemo(() => {",
  '    return editors.map(e => ({ ...e, found: e.detect ? checkDetect(e.cmd) : true }))',
  "  }, [editors])",
  "",
  "  function saveCustom() {",
  "    if (!customCmd.trim()) return",
  "    const ne: EditorDef = { id: 'custom-' + Date.now(), name: customCmd.split(/[\\\\/]/).pop()?.split(' ').shift() || 'Custom', cmd: customCmd, detect: false }",
  "    const updated = [...detectStatus.filter(e => !e.detect), ...[ne]]",
  "    setEditors(updated)",
  "    try { localStorage.setItem(CUSTOM_KEY, JSON.stringify(updated)) } catch {}",
  "    setCustomCmd('')",
  "  }",
  "",
  "  return (",
  '    <div className="setting-section">',
  '      <h4 style={{ marginBottom: 8 }}>📝 External Editor</h4>',
  '      <p style={{ fontSize: 13, color: '"'"'var(--on-surface-variant)'"'"', marginBottom: 12 }}>',
  "        {tx('ext.editor.note')}",
  "      </p>",
  '      <div className="editor-list">',
  "        {detectStatus.map((e, i) => (",
  '          <label className="seg-option" key={i} style={{ display: '"'"'flex'"'"', alignItems: '"'"'center'"'"', gap: 8 }}>',
  '            <input type="radio" name="editor" checked={chosen === e.id}',
  "              onChange={() => { setChosen(e.id); p.onConfigured(e.id); localStorage.setItem('pv:editor-choice', e.id) }} />",
  "            <span>{e.name}</span>",
  '            {!e.detect && <span style={{ fontSize: 10, color: '"'"'var(--on-surface-variant)'"'"' }}>detected</span>}',
  "          </label>",
  "        ))}",
  "      </div>",
  '      <div style={{ marginTop: 8 }}>',
  '        <input value={customCmd} onChange={(e) => setCustomCmd(e.target.value)}',
  "          placeholder='code -g {{file}}:{{line}}' className='input' data-od-id='editor-custom-input' />",
  '        <button className="btn btn-text" onClick={saveCustom}',
  "          data-od-id='editor-add'>{tx('ext.editor.add')}</button>",
  "      </div>",
  "    </div>",
  "  )",
  "}",
  "",
  "function checkDetect(cmd: string): boolean {",
  '  return false',
  "}",
].join(N) + N;

fs.writeFileSync('src/ExternalEditorIntegration.tsx', extEditor, 'utf8');
console.log('2) ExternalEditorIntegration.tsx written:', extEditor.length);